version: '3'

services:
  ################################
  #   Setup react js container
  ################################
  web:
    build: https://github.com/athulmurali/jamnjam-front.git#athulmurali-docker
    expose:
      - 3000
    ports:
      - 3000:3000

  ################################
  #   Setup api server
  ################################
  api:
    build: https://github.com/athulmurali/jamnjam-webserver.git#athulmurali-docker
    ports:
      - 3001:3000
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production

  ################################
  #   Setup nginx load balancer
  ###############################
  nginx:
    image: nginx:latest # this will use the latest version of 1.13.x
    ports:
      - 80:80 # expose 80 on host and sent to 80 in container
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
